import { bsc } from 'viem/chains'
import { createPublicClient, http, parseAbi, type Address, type PublicClient } from 'viem'
const marketAbi = parseAbi(['function supplyRatePerBlock() view returns (uint256)', 'function symbol() view returns (string)'])
const WAD = 10n ** 18n
const BLOCKS_PER_YEAR = 70_080_000n // BSC measured 0.45s blocks; simple annualisation, not APY.
export interface YieldRoute { market: `0x${string}`; symbol: string; supplyRatePerBlock: string; simpleAnnualRateBps: string }
export interface YieldAssessment { category: 'yield_optimisation'; assessmentVersion: 'venus-yield/v1'; routes: YieldRoute[]; recommendedMarket?: `0x${string}`; recommendation: 'RATE_ONLY_CANDIDATE' | 'INSUFFICIENT_EVIDENCE'; observedAt: string; caveats: string[] }
export function assessYield(routes: YieldRoute[], rateOnly: boolean, observedAt = new Date().toISOString()): YieldAssessment { const best = [...routes].sort((a, b) => BigInt(b.simpleAnnualRateBps) > BigInt(a.simpleAnnualRateBps) ? 1 : -1)[0]; return { category: 'yield_optimisation', assessmentVersion: 'venus-yield/v1', routes, ...(rateOnly && best ? { recommendedMarket: best.market } : {}), recommendation: rateOnly && best ? 'RATE_ONLY_CANDIDATE' : 'INSUFFICIENT_EVIDENCE', observedAt, caveats: ['Rates are live Venus supply rates annualised linearly from BSC blocks; this is not realised APY.', 'No risk, liquidity, gas, depeg, protocol, or withdrawal-delay comparison has been performed.', ...(rateOnly ? ['Rate-only mode is explicitly not an optimisation recommendation.'] : ['Set rateOnly=true only to request a clearly labelled rate-only candidate.'])] } }
export interface YieldReader { assess(markets: `0x${string}`[], rateOnly: boolean): Promise<YieldAssessment> }
export class VenusYieldClient implements YieldReader { private readonly client: PublicClient; constructor(rpcUrl: string, client?: PublicClient) { this.client = client ?? createPublicClient({ chain: bsc, transport: http(rpcUrl) }) } async assess(markets: `0x${string}`[], rateOnly: boolean) { if (!markets.length) throw new Error('At least one Venus market is required.'); const routes = await Promise.all(markets.map(async (market) => { const [rateRaw, symbolRaw] = await Promise.all([this.client.readContract({ address: market as Address, abi: marketAbi, functionName: 'supplyRatePerBlock' }), this.client.readContract({ address: market as Address, abi: marketAbi, functionName: 'symbol' })]); const rate = rateRaw as bigint; return { market, symbol: symbolRaw as string, supplyRatePerBlock: rate.toString(), simpleAnnualRateBps: (rate * BLOCKS_PER_YEAR * 10_000n / WAD).toString() } })); return assessYield(routes, rateOnly) } }
