// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Fixture} from "./base/Fixture.sol";
import {AmountSite, Caveat, Delegation} from "../src/core/Types.sol";
import {EncoderLib} from "../src/core/EncoderLib.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/// @title Parity
/// @notice Replays test/vectors/policy-vectors.json -- generated by driving the REAL
///         `evaluatePolicy` from apps/api/src/authority/policy.ts -- and asserts the chain
///         reaches the identical verdict, the identical `rule` token, and the identical
///         `reason` string for every row.
///
/// @dev THIS IS THE DELIVERABLE THAT MAKES THE T0 CLAIM CHECKABLE. Everything else in this
///      repository is an implementation of a promise; this file is the test of it. A divergence
///      between the API's answer and the chain's answer is a product-level lie, and the only
///      way that stops being a claim and starts being a fact is if a divergence is a red test.
///
///      WHAT THIS PROVES: given the same `(target, selector, asset, amount, at, spent)` tuple
///      and the same constraint list, the on-chain enforcers and `evaluatePolicy` agree on
///      allow/deny, on which constraint denied, and on the sentence shown to the user.
///
///      WHAT THIS DOES NOT PROVE: that the chain derived the right tuple from the raw call.
///      `Action.amount` and `Action.asset` are fields somebody asserts off chain; on chain they
///      come from the signed AmountSite table. Whether that table truthfully describes what a
///      given protocol call does is a compiler and curation property, and no parity test can
///      establish it. The fail-closed behaviour around it is tested in Enforcers.t.sol and
///      Attacks.t.sol instead.
contract ParityTest is Fixture {
    string internal json;

    /// @dev Far-future expiry compiled for rows whose policy carries no expiry constraint. Off
    ///      chain `policy.expiresAt` is then undefined and the check is skipped entirely; on
    ///      chain the manager REQUIRES an expiry caveat, so the harness signs an explicit
    ///      unbounded one. The two agree because "no deadline" and "a deadline past any
    ///      plausible action" produce the same verdict for every row in the corpus.
    uint256 internal constant NO_EXPIRY = type(uint64).max;

    function setUp() public {
        deploySuite();
        json = vm.readFile("./test/vectors/policy-vectors.json");
    }

    /// @dev The hand-written boundary rows sit at the front of the corpus: the empty-allowlist
    ///      inversion, `amount == cap`, `spent + amount == cap`, `at == expiresAt`, and the
    ///      rule-ordering cases. They run as their own test so a boundary regression is
    ///      immediately legible rather than buried in a fuzz sweep.
    function test_Parity_Boundaries() public {
        _runRange(0, 30);
    }

    function test_Parity_Fuzz_A() public {
        _runRange(30, 70);
    }

    function test_Parity_Fuzz_B() public {
        _runRange(70, 110);
    }

    function test_Parity_Fuzz_C() public {
        _runRange(110, 150);
    }

    function test_Parity_Fuzz_D() public {
        _runRange(150, vm.parseJsonUint(json, ".count"));
    }

    /// @notice Guards the corpus itself: an all-denial corpus would be passed by a contract
    ///         that reverts unconditionally, which is not the property under test.
    function test_CorpusExercisesBothVerdicts() public {
        uint256 count = vm.parseJsonUint(json, ".count");
        assertTrue(count > 100, "corpus is too small to anchor a chain-enforcement claim");
        uint256 allows;
        for (uint256 i; i < count; ++i) {
            if (vm.parseJsonBool(json, string.concat(".rows[", vm.toString(i), "].expect.allow"))) allows++;
        }
        emit log_named_uint("vectors in corpus", count);
        emit log_named_uint("   expecting allow", allows);
        assertTrue(allows > count / 5, "corpus does not exercise the allow path enough");
        assertTrue(count - allows > count / 5, "corpus does not exercise the deny path enough");
    }

    function _runRange(uint256 from, uint256 to) internal {
        for (uint256 i = from; i < to; ++i) {
            _runRow(i);
        }
    }

    function _runRow(uint256 index) internal {
        string memory p = string.concat(".rows[", vm.toString(index), "]");
        string memory name = vm.parseJsonString(json, string.concat(p, ".name"));

        address target = vm.parseAddress(vm.parseJsonString(json, string.concat(p, ".action.target")));
        bytes4 selector = parseSelector(vm.parseJsonString(json, string.concat(p, ".action.selector")));
        address asset = vm.parseAddress(vm.parseJsonString(json, string.concat(p, ".action.asset")));
        uint256 amount = vm.parseUint(vm.parseJsonString(json, string.concat(p, ".action.amount")));
        uint256 at = vm.parseUint(vm.parseJsonString(json, string.concat(p, ".action.at")));
        uint256 spent = vm.parseUint(vm.parseJsonString(json, string.concat(p, ".spent")));

        bool expectedAllow = vm.parseJsonBool(json, string.concat(p, ".expect.allow"));
        string memory expectedRule = vm.parseJsonString(json, string.concat(p, ".expect.rule"));
        string memory expectedReason = vm.parseJsonString(json, string.concat(p, ".expect.reason"));

        // Every asset in the corpus is given working ERC-20 code, because the cap enforcers
        // snapshot balanceOf and an asset whose balanceOf does not work is not a token. The
        // fail-closed behaviour when it is not is asserted separately.
        if (asset.code.length == 0) vm.etch(asset, address(token).code);

        // The amount is NOT handed to the enforcers. It is encoded into real calldata at word
        // 1 and decoded back out through the signed site, so AmountLib is genuinely exercised.
        bytes memory callData = abi.encodeWithSelector(selector, recipient, amount);
        bytes memory exec = execOf(target, 0, callData);
        AmountSite[] memory sites = siteFor(target, selector, asset, 1);

        Delegation memory d = _compile(p, asset, sites);
        d.delegate = agent;
        d.salt = index; // one delegation per row, so session counters never bleed across rows
        d.signature = signAs(OWNER_PK, d);

        if (spent != 0) {
            bytes32 h = EncoderLib.hashDelegation(d);
            vm.store(address(sessionE), sessionSpentSlot(address(manager), h), bytes32(spent));
            assertEq(
                sessionE.spentOf(address(manager), h),
                spent,
                string.concat(name, ": failed to seed the session counter (storage layout moved?)")
            );
        }

        vm.warp(at);
        vm.prank(agent);
        (bool allow, string memory rule, string memory reason) = manager.dryRun(d, bytes32(0), exec);

        assertEq(allow, expectedAllow, string.concat(name, ": allow/deny diverges from evaluatePolicy"));
        assertEq(rule, expectedRule, string.concat(name, ": rule diverges from evaluatePolicy"));
        assertEq(reason, expectedReason, string.concat(name, ": reason diverges from evaluatePolicy"));
    }

    /// @dev The policy compiler, in Solidity, for the corpus shape. It is the mapping the real
    ///      TypeScript compiler must implement:
    ///        - exactly one caveat per constraint INSTANCE, in `policy.constraints` order.
    ///          Never merge same-kind allowlists for gas: the off-chain loop ANDs every
    ///          constraint, so two contract_allowlists INTERSECT, and merging them into one
    ///          enforcer turns that intersection into a union and silently widens the mandate.
    ///        - `expiry` hoisted to caveat index 0 and skipped in the walk, because
    ///          `compilePolicy` hoists it out of the loop and `evaluatePolicy` has no expiry
    ///          branch inside the loop at all.
    ///        - `condition` has no branch here and never will. It is an off-chain trigger by
    ///          nature; a mandate containing one cannot be T0.
    function _compile(string memory p, address asset, AmountSite[] memory sites)
        internal
        view
        returns (Delegation memory d)
    {
        uint256 n = vm.parseJsonUint(json, string.concat(p, ".constraintCount"));
        uint256 expirySeconds = vm.parseUint(vm.parseJsonString(json, string.concat(p, ".expirySeconds")));

        Caveat[] memory caveats = new Caveat[](n + 1);
        caveats[0] = expiryCaveat(expirySeconds == 0 ? NO_EXPIRY : expirySeconds);

        uint256 out = 1;
        for (uint256 i; i < n; ++i) {
            string memory cp = string.concat(p, ".constraints[", vm.toString(i), "]");
            string memory kind = vm.parseJsonString(json, string.concat(cp, ".kind"));
            bytes32 k = keccak256(bytes(kind));

            if (k == keccak256("expiry")) continue; // hoisted to index 0

            if (k == keccak256("contract_allowlist")) {
                caveats[out++] = Caveat({
                    enforcer: address(targetsE),
                    terms: packAddresses(_addresses(string.concat(cp, ".values"))),
                    args: ""
                });
            } else if (k == keccak256("selector_allowlist")) {
                caveats[out++] = Caveat({
                    enforcer: address(selectorsE),
                    terms: packSelectors(_selectors(string.concat(cp, ".values"))),
                    args: ""
                });
            } else if (k == keccak256("asset_scope")) {
                caveats[out++] = Caveat({
                    enforcer: address(assetsE),
                    terms: abi.encode(_addresses(string.concat(cp, ".values")), sites),
                    args: ""
                });
            } else if (k == keccak256("per_action_cap")) {
                uint256 cap = vm.parseUint(vm.parseJsonString(json, string.concat(cp, ".cap")));
                caveats[out++] =
                    Caveat({enforcer: address(perActionE), terms: capTerms(asset, cap, sites), args: ""});
            } else if (k == keccak256("session_total_cap")) {
                uint256 cap = vm.parseUint(vm.parseJsonString(json, string.concat(cp, ".cap")));
                caveats[out++] =
                    Caveat({enforcer: address(sessionE), terms: capTerms(asset, cap, sites), args: ""});
            } else {
                revert("corpus contains a constraint kind the compiler must refuse to emit");
            }
        }

        Caveat[] memory trimmed = new Caveat[](out);
        for (uint256 i; i < out; ++i) {
            trimmed[i] = caveats[i];
        }
        d = baseDelegation(address(account), trimmed);
    }

    function _addresses(string memory path) internal view returns (address[] memory out) {
        string[] memory raw = vm.parseJsonStringArray(json, path);
        out = new address[](raw.length);
        for (uint256 i; i < raw.length; ++i) {
            out[i] = vm.parseAddress(raw[i]);
        }
    }

    function _selectors(string memory path) internal view returns (bytes4[] memory out) {
        string[] memory raw = vm.parseJsonStringArray(json, path);
        out = new bytes4[](raw.length);
        for (uint256 i; i < raw.length; ++i) {
            out[i] = parseSelector(raw[i]);
        }
    }
}
